/**
 * Icon manifest — the single source of truth for font generation.
 *
 * `icons` below lists the canonical class names in the exact order used by the
 * original InSales font-generator build, so generated codepoints (starting at
 * 0xE800) are identical to the reference: `icon-angle-down` = "\E800" …
 * `icon-user` = "\E852".
 *
 * Each set maps a canonical name to the SVG file shipped inside the
 * corresponding npm package. Icon sources are NOT copied into this repo —
 * they are resolved from node_modules at build time:
 *
 *   bootstrap bootstrap-icons        icons/<name>[-fill].svg               (MIT)
 *   remix     remixicon              icons/<category>/<name>[-line|-fill].svg (Apache-2.0)
 *   phosphor  @phosphor-icons/core assets/<regular|fill>/<name>[-fill].svg (MIT)
 *
 * Fill variants are marked with a `dir:` prefix (phosphor) or an explicit
 * `-fill` suffix in the file name (bootstrap/remix).
 *
 * A handful of InSales-specific glyphs have no direct counterpart in modern
 * sets; the closest semantic analog is used and noted inline.
 */

export const FONT_NAME = 'insales-icons';
export const CSS_CLASS = 'icon';
export const FIRST_CODEPOINT = 0xe800;

export const icons = [
  'angle-down',
  'angle-left',
  'angle-right',
  'angle-up',
  'arrow-down',
  'arrow-left',
  'arrow-right',
  'arrow-up',
  'bars',
  'bell-slash',
  'bell',
  'calendar',
  'camera',
  'cart',
  'check-square',
  'check',
  'circle',
  'clock',
  'comments',
  'compare',
  'content',
  'credit-card',
  'desktop',
  'dot-circle',
  'ellipsis-h',
  'ellipsis-v',
  'envelope',
  'exchange',
  'exclamation-triangle',
  'exclamation',
  'eye-slash',
  'eye',
  'favorites-f',
  'favorites-o',
  'favorites',
  'file-code-o',
  'filter',
  'folder-open',
  'home',
  'in-cart',
  'info',
  'laptop',
  'life-bouy',
  'location-arrow',
  'long-arrow-down',
  'long-arrow-left',
  'long-arrow-right',
  'long-arrow-up',
  'map-marker',
  'minus-circle',
  'minus',
  'mobile',
  'order',
  'paper-plane',
  'pencil',
  'phone',
  'photo',
  'plus-circle',
  'plus',
  'preorder',
  'question-circle',
  'question',
  'search-minus',
  'search-plus',
  'search',
  'share-alt',
  'shopping-cart',
  'sliders',
  'sort-amount-asc',
  'sort-amount-desc',
  'sort-asc',
  'sort-desc',
  'sort',
  'square-o',
  'square',
  'star-o',
  'star',
  'tasks',
  'times',
  'toggle-off',
  'toggle-on',
  'trash',
  'user',
];

export const sets = {
  bootstrap: {
    label: 'Bootstrap',
    package: 'bootstrap-icons',
    license: 'MIT',
    resolve(file) {
      return `bootstrap-icons/icons/${file}.svg`;
    },
    map: {
      'angle-down': 'chevron-down',
      'angle-left': 'chevron-left',
      'angle-right': 'chevron-right',
      'angle-up': 'chevron-up',
      'arrow-down': 'arrow-down',
      'arrow-left': 'arrow-left',
      'arrow-right': 'arrow-right',
      'arrow-up': 'arrow-up',
      bars: 'list',
      'bell-slash': 'bell-slash',
      bell: 'bell',
      calendar: 'calendar',
      camera: 'camera',
      cart: 'cart',
      'check-square': 'check-square',
      check: 'check',
      circle: 'circle',
      clock: 'clock',
      comments: 'chat-square-text',
      compare: 'bar-chart-line',
      content: 'file-text',
      'credit-card': 'credit-card',
      desktop: 'display',
      'dot-circle': 'record-circle',
      'ellipsis-h': 'three-dots',
      'ellipsis-v': 'three-dots-vertical',
      envelope: 'envelope',
      exchange: 'arrow-left-right',
      'exclamation-triangle': 'exclamation-triangle',
      exclamation: 'exclamation-lg',
      'eye-slash': 'eye-slash',
      eye: 'eye',
      'favorites-f': 'heart-fill',
      'favorites-o': 'heart',
      favorites: 'heart',
      'file-code-o': 'file-code',
      filter: 'funnel',
      'folder-open': 'folder2-open',
      home: 'house',
      'in-cart': 'cart-plus',
      info: 'info-circle',
      laptop: 'laptop',
      'life-bouy': 'life-preserver',
      'location-arrow': 'cursor',
      'long-arrow-down': 'arrow-down',
      'long-arrow-left': 'arrow-left',
      'long-arrow-right': 'arrow-right',
      'long-arrow-up': 'arrow-up',
      'map-marker': 'geo-alt',
      'minus-circle': 'dash-circle',
      minus: 'dash',
      mobile: 'phone',
      order: 'receipt',
      'paper-plane': 'send',
      pencil: 'pencil',
      phone: 'telephone',
      photo: 'image',
      'plus-circle': 'plus-circle',
      plus: 'plus-lg',
      preorder: 'calendar-plus',
      'question-circle': 'question-circle',
      question: 'question-lg',
      'search-minus': 'zoom-out',
      'search-plus': 'zoom-in',
      search: 'search',
      'share-alt': 'share',
      'shopping-cart': 'cart3',
      sliders: 'sliders',
      'sort-amount-asc': 'sort-numeric-down',
      'sort-amount-desc': 'sort-numeric-up',
      'sort-asc': 'sort-up',
      'sort-desc': 'sort-down',
      sort: 'arrow-down-up',
      'square-o': 'square',
      square: 'square-fill',
      'star-o': 'star',
      star: 'star-fill',
      tasks: 'list-check',
      times: 'x-lg',
      'toggle-off': 'toggle-off',
      'toggle-on': 'toggle-on',
      trash: 'trash',
      user: 'person',
    },
  },

  remix: {
    label: 'Remix',
    package: 'remixicon',
    license: 'Apache-2.0',
    // remixicon groups files into category directories; the build script
    // resolves these file names with a recursive search.
    resolve(file) {
      return `remixicon/icons/**/${file}.svg`;
    },
    map: {
      'angle-down': 'arrow-down-s-line',
      'angle-left': 'arrow-left-s-line',
      'angle-right': 'arrow-right-s-line',
      'angle-up': 'arrow-up-s-line',
      'arrow-down': 'arrow-down-line',
      'arrow-left': 'arrow-left-line',
      'arrow-right': 'arrow-right-line',
      'arrow-up': 'arrow-up-line',
      bars: 'menu-line',
      'bell-slash': 'notification-off-line',
      bell: 'notification-3-line',
      calendar: 'calendar-line',
      camera: 'camera-line',
      cart: 'shopping-cart-line',
      'check-square': 'checkbox-line',
      check: 'check-line',
      circle: 'circle-line',
      clock: 'time-line',
      comments: 'chat-3-line',
      compare: 'bar-chart-line',
      content: 'file-list-line',
      'credit-card': 'bank-card-line',
      desktop: 'computer-line',
      'dot-circle': 'radio-button-line',
      'ellipsis-h': 'more-line',
      'ellipsis-v': 'more-2-line',
      envelope: 'mail-line',
      exchange: 'exchange-line',
      'exclamation-triangle': 'alert-line',
      exclamation: 'error-warning-line',
      'eye-slash': 'eye-off-line',
      eye: 'eye-line',
      'favorites-f': 'heart-fill',
      'favorites-o': 'heart-line',
      favorites: 'heart-line',
      'file-code-o': 'file-code-line',
      filter: 'filter-line',
      'folder-open': 'folder-open-line',
      home: 'home-line',
      'in-cart': 'shopping-bag-line',
      info: 'information-line',
      laptop: 'macbook-line',
      'life-bouy': 'lifebuoy-line',
      'location-arrow': 'navigation-line',
      'long-arrow-down': 'arrow-down-line',
      'long-arrow-left': 'arrow-left-line',
      'long-arrow-right': 'arrow-right-line',
      'long-arrow-up': 'arrow-up-line',
      'map-marker': 'map-pin-line',
      'minus-circle': 'indeterminate-circle-line',
      minus: 'subtract-line',
      mobile: 'smartphone-line',
      order: 'receipt-line',
      'paper-plane': 'send-plane-line',
      pencil: 'pencil-line',
      phone: 'phone-line',
      photo: 'image-line',
      'plus-circle': 'add-circle-line',
      plus: 'add-line',
      preorder: 'calendar-todo-line',
      'question-circle': 'question-line',
      question: 'question-mark',
      'search-minus': 'zoom-out-line',
      'search-plus': 'zoom-in-line',
      search: 'search-line',
      'share-alt': 'share-line',
      'shopping-cart': 'shopping-cart-2-line',
      sliders: 'equalizer-line',
      'sort-amount-asc': 'sort-asc',
      'sort-amount-desc': 'sort-desc',
      'sort-asc': 'sort-asc',
      'sort-desc': 'sort-desc',
      sort: 'swap-line',
      'square-o': 'checkbox-blank-line',
      square: 'checkbox-blank-fill',
      'star-o': 'star-line',
      star: 'star-fill',
      tasks: 'list-check',
      times: 'close-line',
      'toggle-off': 'toggle-line',
      'toggle-on': 'toggle-fill',
      trash: 'delete-bin-line',
      user: 'user-line',
    },
  },

  phosphor: {
    label: 'Phosphor',
    package: '@phosphor-icons/core',
    license: 'MIT',
    resolve(file) {
      const [dir, name] = file.includes(':') ? file.split(':') : ['regular', file];
      const suffix = dir === 'fill' ? '-fill' : '';
      return `@phosphor-icons/core/assets/${dir}/${name}${suffix}.svg`;
    },
    map: {
      'angle-down': 'caret-down',
      'angle-left': 'caret-left',
      'angle-right': 'caret-right',
      'angle-up': 'caret-up',
      'arrow-down': 'arrow-down',
      'arrow-left': 'arrow-left',
      'arrow-right': 'arrow-right',
      'arrow-up': 'arrow-up',
      bars: 'list',
      'bell-slash': 'bell-slash',
      bell: 'bell',
      calendar: 'calendar',
      camera: 'camera',
      cart: 'shopping-cart-simple',
      'check-square': 'check-square',
      check: 'check',
      circle: 'circle',
      clock: 'clock',
      comments: 'chats',
      compare: 'chart-bar',
      content: 'textbox',
      'credit-card': 'credit-card',
      desktop: 'monitor',
      'dot-circle': 'record',
      'ellipsis-h': 'dots-three',
      'ellipsis-v': 'dots-three-vertical',
      envelope: 'envelope',
      exchange: 'arrows-left-right',
      'exclamation-triangle': 'warning',
      exclamation: 'exclamation-mark',
      'eye-slash': 'eye-slash',
      eye: 'eye',
      'favorites-f': 'fill:heart',
      'favorites-o': 'heart',
      favorites: 'heart',
      'file-code-o': 'file-code',
      filter: 'funnel',
      'folder-open': 'folder-open',
      home: 'house',
      'in-cart': 'basket',
      info: 'info',
      laptop: 'laptop',
      'life-bouy': 'lifebuoy',
      'location-arrow': 'navigation-arrow',
      'long-arrow-down': 'arrow-down',
      'long-arrow-left': 'arrow-left',
      'long-arrow-right': 'arrow-right',
      'long-arrow-up': 'arrow-up',
      'map-marker': 'map-pin',
      'minus-circle': 'minus-circle',
      minus: 'minus',
      mobile: 'device-mobile',
      order: 'receipt',
      'paper-plane': 'paper-plane-tilt',
      pencil: 'pencil-simple',
      phone: 'phone',
      photo: 'image',
      'plus-circle': 'plus-circle',
      plus: 'plus',
      preorder: 'calendar-plus',
      'question-circle': 'question',
      question: 'question-mark',
      'search-minus': 'magnifying-glass-minus',
      'search-plus': 'magnifying-glass-plus',
      search: 'magnifying-glass',
      'share-alt': 'share-network',
      'shopping-cart': 'shopping-cart',
      sliders: 'sliders',
      'sort-amount-asc': 'sort-ascending',
      'sort-amount-desc': 'sort-descending',
      'sort-asc': 'sort-ascending',
      'sort-desc': 'sort-descending',
      sort: 'arrows-down-up',
      'square-o': 'square',
      square: 'fill:square',
      'star-o': 'star',
      star: 'fill:star',
      tasks: 'list-checks',
      times: 'x',
      'toggle-off': 'toggle-left',
      'toggle-on': 'toggle-right',
      trash: 'trash',
      user: 'user',
    },
  },
};
