/**
 * Demo data template — a classic-script file (loaded via <script src> so it
 * works from file://) exposing the manifest data to the static demo page.
 *
 * @param {object} options
 * @param {string} options.fontName  font-family shared by every set
 * @param {number} options.firstCodepoint  codepoint of the first glyph
 * @param {Array<{key: string, label: string, packageName: string, license: string, icons: string[]}>} options.sets
 * @returns {string} JavaScript contents
 */
export function renderDemoData({ fontName, firstCodepoint, sets }) {
  const data = {
    fontName,
    firstCodepoint,
    sets: sets.map(({ key, label, packageName, license, icons }) => ({
      key,
      label,
      package: packageName,
      license,
      icons,
    })),
  };

  return `// Generated by "npm run fonts" from config/icons.mjs — do not edit.
window.insalesIcons = ${JSON.stringify(data, null, 2)};
`;
}
